title: "Callum Truscott"
email: callum@thetruscotts.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/thespinogamer.github.io" 
# twitter_username: mlhacks
github_username:  TheSpinoGamer

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

collections:
  - projects

exclude: [vendor]
